// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sample.Infrastructure.Orders.DbContexts;

#nullable disable

namespace Sample.Infrastructure.Orders.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20240906154720_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sample.Core.Order.Model.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("OrderNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id", "OrderNumber");

                    b.HasIndex("OrderNumber");

                    b.ToTable("Orders", "orders");
                });

            modelBuilder.Entity("Sample.Infrastructure.Orders.Model.OutBox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long>("CreatedAtTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("ProcessedAtTimestamp")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtTimestamp");

                    b.HasIndex("ProcessedAtTimestamp");

                    b.ToTable("OutBox", "orders");
                });

            modelBuilder.Entity("Sample.Core.Order.Model.Order", b =>
                {
                    b.OwnsMany("Sample.Core.Order.Model.OrderItem", "Items", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<long>("OrderNumber")
                                .HasColumnType("bigint");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<Guid>("ItemId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer");

                            b1.HasKey("OrderId", "OrderNumber", "Id");

                            b1.ToTable("Orders", "orders");

                            b1.ToJson("Items");

                            b1.WithOwner()
                                .HasForeignKey("OrderId", "OrderNumber");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
